package io.github.viniciusgaspari.GamesLibraryApi.model;

public enum Nacionalidade {
    ALEMA,
    AMERICANA,
    ANGOLANA,
    ARGENTINA,
    AUSTRALIANA,
    BELGA,
    BRASILEIRA,
    CANADENSE,
    CHILENA,
    CHINESA,
    COLOMBIANA,
    COREANA,
    CUBANA,
    DINAMARQUESA,
    EGIPCIA,
    ESPANHOLA,
    FRANCESA,
    GREGA,
    HOLANDESA,
    INDIANA,
    INGLESA,
    ITALIANA,
    JAPONESA,
    LIBANESA,
    MEXICANA,
    MOCAMBICANA,
    NORUEGUESA,
    PARAGUAIA,
    PERUANA,
    PORTUGUESA,
    RUSSA,
    SUECA,
    SUICA,
    URUGUAIA,

}
