spring:
  application:
    name: CursoDougllas Sousa

  datasource:
    url: jdbc:postgresql://localhost:5432/erpdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format-sql: true